// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkisxCiMnRCE2Y_mO_PEZCrSM_mUb7oLs',
    appId: '1:213808474905:web:6f6b612c7fe0c46865f388',
    messagingSenderId: '213808474905',
    projectId: 'runard-d4b37',
    authDomain: 'runard-d4b37.firebaseapp.com',
    storageBucket: 'runard-d4b37.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJEH4nQc6sSX8bz3a7kDfEwDtcWfK2J20',
    appId: '1:213808474905:android:22cc51d7daa5e77565f388',
    messagingSenderId: '213808474905',
    projectId: 'runard-d4b37',
    storageBucket: 'runard-d4b37.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDybhY9V6AMAmgkyJ-P-SdGVaOHBzbG3hE',
    appId: '1:213808474905:ios:d495488fda45a8b265f388',
    messagingSenderId: '213808474905',
    projectId: 'runard-d4b37',
    storageBucket: 'runard-d4b37.appspot.com',
    iosClientId: '213808474905-3herrnngi1qhtu59ptai9ekjls4m9smt.apps.googleusercontent.com',
    iosBundleId: 'com.example.runard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDybhY9V6AMAmgkyJ-P-SdGVaOHBzbG3hE',
    appId: '1:213808474905:ios:d495488fda45a8b265f388',
    messagingSenderId: '213808474905',
    projectId: 'runard-d4b37',
    storageBucket: 'runard-d4b37.appspot.com',
    iosClientId: '213808474905-3herrnngi1qhtu59ptai9ekjls4m9smt.apps.googleusercontent.com',
    iosBundleId: 'com.example.runard',
  );
}
